apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rusty-tusks
    app.kubernetes.io/part-of: rusty-tusks
  name: rusty-tusks-walrus-explorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: walrus-explorer
subjects:
- kind: ServiceAccount
  name: rusty-tusks
  namespace: rusty-tusks
